all: AggregationServer.class ContentServer.class GETClient.class

AggregationServer.class: AggregationServer.java
		javac $<

ContentServer.class: ContentServer.java
		javac $<

GETClient.class: GETClient.java
		javac $<

clean:
		rm -rf *.class